name = "Cached"
uuid = "1b238080-9255-4fe9-b224-89eb24efe93b"
version = "0.1.0"
authors = ["Lukas Devos <ldevos98@gmail.com> and contributors"]

[compat]
julia = "1.10"

[workspace]
projects = ["test", "docs", "benchmark"]
