"""
    Cached.implementation(f, args...; kwargs...)

The uncached body of a [`@cached`](@ref) function `f`. The macro moves the body of each cached
method here, dispatching on `typeof(f)`; call it through [`uncached`](@ref).
"""
function implementation end

"""
    uncached(f, args...; kwargs...)

Call the [`@cached`](@ref) function `f` without consulting or filling any cache.
"""
uncached(f, args...; kwargs...) = implementation(f, args...; kwargs...)

_callimpl(f, args, kw) = implementation(f, args...; kw...)

# Entry point of the methods generated by `@cached`. `vt` is the return type annotation, or
# `nothing` when there is none, in which case the value type is inferred.
@inline call(f::F, style::CacheStyle, ::Type{V}, args::Tuple, kw::NamedTuple) where {F, V} =
    _call(f, style, V, _key(args, kw), args, kw)
@inline call(f::F, style::CacheStyle, ::Nothing, args::A, kw::KW) where {F, A <: Tuple, KW <: NamedTuple} =
    _call(f, style, _inferred_valtype(Core.Compiler.return_type(_callimpl, Tuple{F, A, KW})), _key(args, kw), args, kw)

_inferred_valtype(::Type{V}) where {V} = isconcretetype(V) ? V : Any

_key(args::Tuple, ::NamedTuple{()}) = args
_key(args::Tuple, kw::NamedTuple) = (args..., kw)

_call(f, ::NoCache, ::Type, key, args, kw) = implementation(f, args...; kw...)

# The cache holds keys and values of any type; the assertion recovers the value type, so that
# calls stay inferred. Lookups do not box the key (see `Key`).
function _call(f::F, ::GlobalCache{C}, ::Type{V}, key, args, kw) where {F, C, V}
    cache = globalcache(f, C{Any, Any})::C{Any, Any}
    return get!(() -> implementation(f, args...; kw...), cache, key)::V
end

function _call(f::F, ::TaskLocalCache{C}, ::Type{V}, key::K, args, kw) where {F, C, V, K}
    T = _localtype(C, K, V)
    table = get!(IdDict{Any, Any}, task_local_storage(), :__Cached_tasklocal__)::IdDict{Any, Any}
    cache = get!(() -> _newlocal(f, T), table, (f, T))::T
    return get!(() -> implementation(f, args...; kw...), cache, key)::V
end

# One untyped cache per function for the containers of Cached; other dictionaries (e.g. `Dict`)
# would box untyped keys, so they get one typed dictionary per key and value type.
_localtype(C, K, V) = C isa UnionAll ? (C <: AbstractCache ? C{Any, Any} : C{K, V}) : C
# Task-local caches follow the size settings of `f`, but are not registered.
function _newlocal(f, ::Type{T}) where {T <: AbstractCache}
    fc = @lock REGISTRY.lock _functioncaches!(f)
    return T(; maxsize = fc.maxsize, by = fc.by)
end
_newlocal(f, ::Type{T}) where {T} = T()
