"""
    Cached.implementation(f, args...; kwargs...)

The uncached body of a [`@cached`](@ref) function `f`. The macro moves the body of each cached
method here, dispatching on `typeof(f)`; call it through [`uncached`](@ref).
"""
function implementation end

"""
    uncached(f, args...; kwargs...)

Call the [`@cached`](@ref) function `f` without consulting or filling any cache.
"""
uncached(f, args...; kwargs...) = implementation(f, args...; kwargs...)

# Hook around the phases of a call, for `enable_cache_timers!` (TimerOutputs extension):
# `:lookup` wraps the whole cache lookup, hit or miss, and `:compute` the implementation call,
# nested in `:lookup` on a miss and alone under `NoCache`. `owner` is the package owning `f`,
# folded at compile time; the extension defines a method per owner, and the default compiles away.
@inline instrument(f, phase, thunk, owner) = thunk()

# The package containing `m`; modules outside packages (in `Main`) own their functions themselves.
_owner(m::Module) = (r = Base.moduleroot(m)) === Main ? m : r
@generated _ownerval(::Type{F}) where {F} = :(Val{$(fullname(_owner(parentmodule(F))))}())

"""
    Cached.instrument_label(f, ::Val{phase}) -> String

Label of the `phase` of `f` in the sections recorded by [`enable_cache_timers!`](@ref).
Defaults to `"lookup f"` and `"compute f"`, with the name of `f`; overload it to choose your own.
"""
instrument_label(f, ::Val{phase}) where {phase} = string(phase, ' ', _fname(f))

_callimpl(f, args, kw) = implementation(f, args...; kw...)

# Entry point of the methods generated by `@cached`. `vt` is the return type annotation, or
# `nothing` when there is none, in which case the value type is inferred.
@inline call(f::F, style::CacheStyle, ::Type{V}, args::Tuple, kw::NamedTuple) where {F, V} =
    _call(f, style, V, _key(args, kw), args, kw)
@inline call(f::F, style::CacheStyle, ::Nothing, args::A, kw::KW) where {F, A <: Tuple, KW <: NamedTuple} =
    _call(f, style, _inferred_valtype(Core.Compiler.return_type(_callimpl, Tuple{F, A, KW})), _key(args, kw), args, kw)

_inferred_valtype(::Type{V}) where {V} = isconcretetype(V) ? V : Any

_key(args::Tuple, ::NamedTuple{()}) = args
_key(args::Tuple, kw::NamedTuple) = (args..., kw)

# `f::F` forces specialization on the function, which Julia skips for `Function` arguments that
# are only passed along; without it the closures would box `f` and allocate. The owner `o` is
# computed outside the closures, which Julia 1.10 otherwise boxes in the first caller compiled.
@inline _compute(f::F, o, args, kw) where {F} = instrument(f, Val(:compute), () -> implementation(f, args...; kw...), o)

_call(f::F, ::NoCache, ::Type{V}, key, args, kw) where {F, V} = _compute(f, _ownerval(F), args, kw)::V

# The cache holds keys and values of any type; the assertion recovers the value type, so that
# calls stay inferred. Lookups do not box the key (see `Key`).
@inline function _call(f::F, style::CacheStyle, ::Type{V}, key, args, kw) where {F, V}
    o = _ownerval(F)
    return instrument(f, Val(:lookup), () -> get!(() -> _compute(f, o, args, kw), _container(f, style, key, V), key), o)::V
end

_container(f::F, ::GlobalCache{C}, key, ::Type) where {F, C} = globalcache(f, C{Any, Any})::C{Any, Any}

function _container(f::F, ::TaskLocalCache{C}, key::K, ::Type{V}) where {F, C, K, V}
    T = _localtype(C, K, V)
    table = get!(IdDict{Any, Any}, task_local_storage(), :__Cached_tasklocal__)::IdDict{Any, Any}
    return get!(() -> _newlocal(f, T), table, (f, T))::T
end

# One untyped cache per function for the containers of Cached; other dictionaries (e.g. `Dict`)
# would box untyped keys, so they get one typed dictionary per key and value type.
_localtype(C, K, V) = C isa UnionAll ? (C <: AbstractCache ? _localcache(C){Any, Any} : C{K, V}) : C
# A task-local cache is used by one task only, so lock-free hits gain nothing there, while the
# per-thread counters of `ClockCache` would cost memory in every task.
_localcache(C) = C === ClockCache ? LocalClockCache : C
# Task-local caches follow the size settings of `f`, but are not registered.
function _newlocal(f, ::Type{T}) where {T <: AbstractCache}
    fc = @lock REGISTRY.lock _functioncaches!(f)
    return T(; maxsize = fc.maxsize, by = fc.by)
end
_newlocal(f, ::Type{T}) where {T} = T()
